Param ()

$env:SYSTEM_COLLECTIONID
$env:SYSTEM_TEAMPROJECT
$env:AGENT_WORKFOLDER
$env:SYSTEM_DEFINITIONID
$env:BUILD_REPOSITORY_NAME
$env:BUILD_REPOSITORY_PROVIDER
$env:BUILD_REPOSITORY_LOCALPATH

Write-Host "Updating BUILD_REPOSITORY_LOCALPATH"

[Environment]::SetEnvironmentVariable("BUILD_REPOSITORY_LOCALPATH", $foo, "User")