Param ()

$env:SYSTEM_COLLECTIONID
$env:SYSTEM_TEAMPROJECT
$env:AGENT_WORKFOLDER
$env:SYSTEM_DEFINITIONID
$env:BUILD_REPOSITORY_NAME
$env:BUILD_REPOSITORY_PROVIDER
$env:BUILD_REPOSITORY_LOCALPATH

Write-Host "Updating PIPELINES_REPOSITORY_PATH"

[Environment]::SetEnvironmentVariable("PIPELINES_REPOSITORY_PATH", "foo", "User")